version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5436:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  db_data: