version: '3.9'

services:
  vk-test-task:
    build: .
    image: vk-test-task:latest
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR_NAME=value
      - DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
    volumes:
      - .:/app
    command: ["./cmd/vk-test-task"]
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://postgres:postgres@db/postgres?sslmode=disable",
      "up"
    ]
    depends_on:
      - db

volumes:
  postgres_data: